### ISSUE TITLE
.travis.yml 常用配置

### ISSUE THREAD

**Issue by noyobo** [noyobo/noyobo.github.com#6]

**Comment by noyobo** [comment]
```yml
language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "node"

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

script:
  - npm run lint
  - npm test

after_script:
  - npm run codecov

notifications:
  email:
  - noyobo@gmail.com
```

**Comment by noyobo** [comment]
```yml
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
```

**Comment by noyobo** [comment]
```yml
codecov:
  branch: master

comment:
  layout: "header, diff"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null
```
